/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.sun.glass.events.KeyEvent;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class DiaPay extends javax.swing.JDialog {

    /**
     * Creates new form DiaPay
     */
    public DiaPay(FrEmployeeWorkspace parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        
        this.setTitle("Paying Table: " + this.parent.cur_table);
        this.setLocationRelativeTo(this.parent);
        this.setLocation(450, 240);
        this.setModal(true);
        initComponents();
        
        try {
            Font customFont = Font.createFont(Font.TRUETYPE_FONT, new File("src/font/FRESHBOT.ttf")).deriveFont(50f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, new File("src/font/FRESHBOT.ttf")));
            ge.getAvailableFontFamilyNames();
            this.lbShow.setFont(customFont);
        } catch (IOException|FontFormatException e) {
            //Handle exception
            e.printStackTrace();
        }
        
        this.lbShow.setText(String.valueOf(this.parent.getOrderofTable(this.parent.cur_table).getKey().getPrice()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnKeyBoard = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnPoint = new javax.swing.JButton();
        btnEnter = new javax.swing.JButton();
        pnInput = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbShow = new javax.swing.JLabel();
        txtCustomerpay = new javax.swing.JTextField();
        txtPayback = new javax.swing.JTextField();
        btnDel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnKeyBoard.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnOK.setText("OK");
        btnOK.setEnabled(false);
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        btnOK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnOKKeyPressed(evt);
            }
        });
        jPanel1.add(btnOK);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);

        jPanel2.setLayout(new java.awt.GridLayout(4, 3));

        btnSeven.setText("7");
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });
        jPanel2.add(btnSeven);

        btnEight.setText("8");
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });
        jPanel2.add(btnEight);

        btnNine.setText("9");
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });
        jPanel2.add(btnNine);

        btnFour.setText("4");
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });
        jPanel2.add(btnFour);

        btnFive.setText("5");
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });
        jPanel2.add(btnFive);

        btnSix.setText("6");
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });
        jPanel2.add(btnSix);

        btnOne.setText("1");
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });
        jPanel2.add(btnOne);

        btnTwo.setText("2");
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });
        jPanel2.add(btnTwo);

        btnThree.setText("3");
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });
        jPanel2.add(btnThree);

        btnZero.setText("0");
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });
        jPanel2.add(btnZero);

        btnPoint.setText(".");
        btnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPointActionPerformed(evt);
            }
        });
        jPanel2.add(btnPoint);

        btnEnter.setText("ENTER");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });
        jPanel2.add(btnEnter);

        javax.swing.GroupLayout pnKeyBoardLayout = new javax.swing.GroupLayout(pnKeyBoard);
        pnKeyBoard.setLayout(pnKeyBoardLayout);
        pnKeyBoardLayout.setHorizontalGroup(
            pnKeyBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );
        pnKeyBoardLayout.setVerticalGroup(
            pnKeyBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnKeyBoardLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnKeyBoard, java.awt.BorderLayout.CENTER);

        pnInput.setBackground(new java.awt.Color(153, 153, 153));
        pnInput.setPreferredSize(new java.awt.Dimension(400, 140));

        jLabel1.setText("Customer Pay:");

        jLabel2.setText("Pay back:");

        lbShow.setBackground(new java.awt.Color(0, 0, 0));
        lbShow.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbShow.setForeground(new java.awt.Color(0, 204, 0));
        lbShow.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbShow.setOpaque(true);

        txtCustomerpay.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCustomerpay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustomerpayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustomerpayFocusLost(evt);
            }
        });
        txtCustomerpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerpayActionPerformed(evt);
            }
        });

        txtPayback.setEditable(false);
        txtPayback.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnDel.setText("Del");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnInputLayout = new javax.swing.GroupLayout(pnInput);
        pnInput.setLayout(pnInputLayout);
        pnInputLayout.setHorizontalGroup(
            pnInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbShow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnInputLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(pnInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCustomerpay, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPayback, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDel)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        pnInputLayout.setVerticalGroup(
            pnInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInputLayout.createSequentialGroup()
                .addComponent(lbShow, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(pnInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCustomerpay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDel))
                .addGap(15, 15, 15)
                .addGroup(pnInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPayback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnInput, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerpayActionPerformed
        // TODO add your handling code here:
        if(!this.txtCustomerpay.getText().isEmpty()){
            try{
                float price = Float.parseFloat(this.lbShow.getText().trim());
                float cuspay = Float.parseFloat(this.txtCustomerpay.getText().trim());
                if(cuspay < price){
                    JOptionPane.showConfirmDialog(null, "Input error! Please do it again!");
                    this.txtCustomerpay.requestFocus();
                    return;
                }
                float payback = cuspay - price;
                this.txtPayback.setText(String.valueOf(payback));
                this.btnOK.setEnabled(true);
                this.btnOK.requestFocus();
            }catch(NumberFormatException ex){
                JOptionPane.showConfirmDialog(null, "Input error! Please do it again!");
                this.txtCustomerpay.requestFocus();
                return;
            }
        }
    }//GEN-LAST:event_txtCustomerpayActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        this.parent.getOrderofTable(this.parent.cur_table).getKey().setCustomerpay(Float.parseFloat(this.txtCustomerpay.getText().trim()));
        this.parent.getOrderofTable(this.parent.cur_table).getKey().setPayback(Float.parseFloat(this.txtPayback.getText().trim()));
        this.parent.ispay = true;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        // TODO add your handling code here:
        this.txtCustomerpay.requestFocus();
        String text = this.txtCustomerpay.getText();
        text += "0";
        this.txtCustomerpay.setText(text);
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPointActionPerformed
        // TODO add your handling code here:
        this.txtCustomerpay.requestFocus();
        String text = this.txtCustomerpay.getText();
        text += ".";
        this.txtCustomerpay.setText(text);
    }//GEN-LAST:event_btnPointActionPerformed

    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        // TODO add your handling code here:
        String text = this.txtCustomerpay.getText();
        text += "1";
        this.txtCustomerpay.setText(text);
    }//GEN-LAST:event_btnOneActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        // TODO add your handling code here:
        this.txtCustomerpay.requestFocus();
        String text = this.txtCustomerpay.getText();
        text += "2";
        this.txtCustomerpay.setText(text);
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
        // TODO add your handling code here:
        this.txtCustomerpay.requestFocus();
        String text = this.txtCustomerpay.getText();
        text += "3";
        this.txtCustomerpay.setText(text);
    }//GEN-LAST:event_btnThreeActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
        // TODO add your handling code here:
        this.txtCustomerpay.requestFocus();
        String text = this.txtCustomerpay.getText();
        text += "4";
        this.txtCustomerpay.setText(text);
    }//GEN-LAST:event_btnFourActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
        // TODO add your handling code here:
        this.txtCustomerpay.requestFocus();
        String text = this.txtCustomerpay.getText();
        text += "5";
        this.txtCustomerpay.setText(text);
    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
        // TODO add your handling code here:
        this.txtCustomerpay.requestFocus();
        String text = this.txtCustomerpay.getText();
        text += "6";
        this.txtCustomerpay.setText(text);
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
        // TODO add your handling code here:
        this.txtCustomerpay.requestFocus();
        String text = this.txtCustomerpay.getText();
        text += "7";
        this.txtCustomerpay.setText(text);
    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
        // TODO add your handling code here:
        this.txtCustomerpay.requestFocus();
        String text = this.txtCustomerpay.getText();
        text += "8";
        this.txtCustomerpay.setText(text);
    }//GEN-LAST:event_btnEightActionPerformed

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineActionPerformed
        // TODO add your handling code here:
        this.txtCustomerpay.requestFocus();
        String text = this.txtCustomerpay.getText();
        text += "9";
        this.txtCustomerpay.setText(text);
    }//GEN-LAST:event_btnNineActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
        if(!this.txtCustomerpay.getText().isEmpty()){
            try{
                float price = Float.parseFloat(this.lbShow.getText().trim());
                float cuspay = Float.parseFloat(this.txtCustomerpay.getText().trim());
                if(cuspay < price){
                    JOptionPane.showConfirmDialog(null, "Input error! Please do it again!");
                    this.txtCustomerpay.requestFocus();
                    return;
                }
                float payback = cuspay - price;
                this.txtPayback.setText(String.valueOf(payback));
                this.btnOK.setEnabled(true);
            }catch(NumberFormatException ex){
                JOptionPane.showConfirmDialog(null, "Input error! Please do it again!");
                this.txtCustomerpay.requestFocus();
                return;
            }
        }
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        this.txtCustomerpay.requestFocus();
        String text = this.txtCustomerpay.getText();
        if(text.length() > 0){
            text = String.copyValueOf(text.toCharArray(), 0, text.length()-1);
            this.txtCustomerpay.setText(text);
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void txtCustomerpayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerpayFocusGained
        // TODO add your handling code here:
        this.btnOK.setEnabled(false);
    }//GEN-LAST:event_txtCustomerpayFocusGained

    private void txtCustomerpayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerpayFocusLost
        // TODO add your handling code here:
        if(!this.txtCustomerpay.getText().isEmpty()){
            try{
                float price = Float.parseFloat(this.lbShow.getText().trim());
                float cuspay = Float.parseFloat(this.txtCustomerpay.getText().trim());
                if(cuspay < price){
                    this.txtCustomerpay.requestFocus();
                    return;
                }
                float payback = cuspay - price;
                this.txtPayback.setText(String.valueOf(payback));
                this.btnOK.setEnabled(true);
            }catch(NumberFormatException ex){
                this.txtCustomerpay.requestFocus();
                return;
            }
        }
    }//GEN-LAST:event_txtCustomerpayFocusLost

    private void btnOKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnOKKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.parent.getOrderofTable(this.parent.cur_table).getKey().setCustomerpay(Float.parseFloat(this.txtCustomerpay.getText().trim()));
            this.parent.getOrderofTable(this.parent.cur_table).getKey().setPayback(Float.parseFloat(this.txtPayback.getText().trim()));
            this.parent.ispay = true;
            setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_btnOKKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiaPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiaPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiaPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiaPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiaPay dialog = new DiaPay(new FrEmployeeWorkspace(null), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnPoint;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnZero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbShow;
    private javax.swing.JPanel pnInput;
    private javax.swing.JPanel pnKeyBoard;
    private javax.swing.JTextField txtCustomerpay;
    private javax.swing.JTextField txtPayback;
    // End of variables declaration//GEN-END:variables

    FrEmployeeWorkspace parent;
}
