/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.admin.FrAdminWorkspace;
import gui.employee.FrEmployeeWorkspace;
import entities.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.LineNumberReader;
import java.io.ObjectOutputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import model.*;
/**
 *
 * @author Administrator
 */
public class FrLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrLogin
     */
    public FrLogin() {
        
        initComponents();
        
        this.loadingExistedDB();
        
        this.setLocationRelativeTo(this);
        
        this.setFrameIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblogin = new javax.swing.JLabel();
        lbUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbUsername_warn = new javax.swing.JLabel();
        lbPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnDBSelect = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lbPass_warn = new javax.swing.JLabel();
        btnFirstusing = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("C-System");
        setBackground(new java.awt.Color(13, 21, 41));

        jPanel2.setBackground(new java.awt.Color(13, 21, 41));

        lblogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblogin.setForeground(new java.awt.Color(171, 180, 202));
        lblogin.setText("Login Form");

        lbUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbUsername.setForeground(new java.awt.Color(171, 180, 202));
        lbUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/username_icon.png"))); // NOI18N

        txtUsername.setBackground(new java.awt.Color(13, 21, 41));
        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(171, 180, 202));
        txtUsername.setToolTipText("username");
        txtUsername.setBorder(null);
        txtUsername.setEnabled(false);
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        lbUsername_warn.setForeground(new java.awt.Color(255, 0, 0));

        lbPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbPass.setForeground(new java.awt.Color(171, 180, 202));
        lbPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/password_icon.png"))); // NOI18N

        txtPass.setBackground(new java.awt.Color(13, 21, 41));
        txtPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPass.setForeground(new java.awt.Color(171, 180, 202));
        txtPass.setToolTipText("password");
        txtPass.setBorder(null);
        txtPass.setEnabled(false);
        txtPass.setRequestFocusEnabled(false);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(402, 35));
        jPanel1.setLayout(new java.awt.GridLayout());

        btnDBSelect.setBackground(new java.awt.Color(40, 46, 63));
        btnDBSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/database_icon.png"))); // NOI18N
        btnDBSelect.setToolTipText("Select Database");
        btnDBSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDBSelectActionPerformed(evt);
            }
        });
        btnDBSelect.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDBSelectKeyPressed(evt);
            }
        });
        jPanel1.add(btnDBSelect);
        this.btnDBSelect.requestFocus();

        btnSubmit.setBackground(new java.awt.Color(40, 46, 63));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 0, 14));
        btnSubmit.setFont(btnSubmit.getFont().deriveFont(Font.BOLD));
        btnSubmit.setForeground(new java.awt.Color(171, 180, 202));
        btnSubmit.setText("Login");
        btnSubmit.setEnabled(false);
        btnSubmit.setSelected(true);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        btnSubmit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSubmitKeyPressed(evt);
            }
        });
        jPanel1.add(btnSubmit);

        btnCancel.setBackground(new java.awt.Color(40, 46, 63));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(171, 180, 202));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);

        lbPass_warn.setForeground(new java.awt.Color(255, 0, 0));

        btnFirstusing.setBackground(new java.awt.Color(40, 46, 63));
        btnFirstusing.setForeground(new java.awt.Color(171, 180, 202));
        btnFirstusing.setText("Reset History");
        btnFirstusing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstusingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lbPass_warn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPass)
                            .addComponent(lbUsername))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 27, Short.MAX_VALUE))
                            .addComponent(jSeparator2)
                            .addComponent(lbUsername_warn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFirstusing))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(lblogin)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblogin)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbUsername_warn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPass_warn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnFirstusing))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        this.lbUsername_warn.setText("");
        this.lbPass_warn.setText("");
        
        String username = this.txtUsername.getText().trim();
        String pass = new String(this.txtPass.getPassword());
        if(username.isEmpty() || username.length() > 50){
            this.lbUsername_warn.setText("Username is not match the pattern!");
            this.txtUsername.requestFocus();
            return;
        }
        
        if(pass.isEmpty() || pass.length() > 50){
            this.lbPass_warn.setText("Password is not match the pattern!");
            this.txtPass.requestFocus();
            return;
        }
        
        Admin ad = AdminDAO.check(username, pass);              // tiến hành đăng nhập cho admin trước nếu có
        if(ad != null)
        {
            JFrame jf = new FrAdminWorkspace(ad);
            jf.setVisible(true);
            jf.setExtendedState(JFrame.MAXIMIZED_BOTH);
            this.dispose();
            return;
        }
        
        Employee emp = EmployeeDAO.check(username, pass);       // sau đó tiến hành đăng nhập cho nhân viên
        if(emp != null)
        {
            JFrame jf = new FrEmployeeWorkspace(emp);
            jf.setVisible(true);
            jf.setExtendedState(JFrame.MAXIMIZED_BOTH);
            this.dispose();
            return;
        }
        
        JOptionPane.showConfirmDialog(null, "Login fail! Please check your Username and Password!", "LOGIN WARNING", JOptionPane.CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        this.txtUsername.requestFocus();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
        this.txtPass.requestFocus();
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
        this.btnSubmit.requestFocus();
    }//GEN-LAST:event_txtPassActionPerformed

    private void btnSubmitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSubmitKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.lbUsername_warn.setText("");
            this.lbPass_warn.setText("");

            String username = this.txtUsername.getText().trim();
            String pass = new String(this.txtPass.getPassword());
            if(username.isEmpty() || username.length() > 50){
                this.lbUsername_warn.setText("Username is not match the pattern!");
                this.txtUsername.requestFocus();
                return;
            }

            if(pass.isEmpty() || pass.length() > 50){
                this.lbPass_warn.setText("Password is not match the pattern!");
                this.txtPass.requestFocus();
                return;
            }

            Admin ad = AdminDAO.check(username, pass);              // tiến hành đăng nhập cho admin trước nếu có
            if(ad != null)
            {
                JFrame jf = new FrAdminWorkspace(ad);
                jf.setVisible(true);
                jf.setExtendedState(JFrame.MAXIMIZED_BOTH);
                this.dispose();
                return;
            }

            Employee emp = EmployeeDAO.check(username, pass);       // sau đó tiến hành đăng nhập cho nhân viên
            if(emp != null)
            {
                JFrame jf = new FrEmployeeWorkspace(emp);
                jf.setVisible(true);
                jf.setExtendedState(JFrame.MAXIMIZED_BOTH);
                this.dispose();
                return;
            }

            JOptionPane.showConfirmDialog(null, "Login fail! Please check your Username and Password!", "LOGIN WARNING", JOptionPane.CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
            this.txtUsername.requestFocus();
        }
    }//GEN-LAST:event_btnSubmitKeyPressed

    private void btnDBSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDBSelectActionPerformed
        // TODO add your handling code here:
        new DiaDatabaseInfo(this, true).setVisible(true);
        this.loadingExistedDB();
    }//GEN-LAST:event_btnDBSelectActionPerformed

    private void btnDBSelectKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDBSelectKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            new DiaDatabaseInfo(this, true).setVisible(true);
            this.loadingExistedDB();
        }
    }//GEN-LAST:event_btnDBSelectKeyPressed

    private void btnFirstusingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstusingActionPerformed
        // TODO add your handling code here:
        try {
            FileOutputStream fos = new FileOutputStream("src/textfile/history.txt");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            
            oos.writeBoolean(true);
            
            oos.close();
            fos.close();
            
            this.btnFirstusing.setBackground(Color.GREEN);
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnFirstusingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDBSelect;
    private javax.swing.JButton btnFirstusing;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbPass;
    private javax.swing.JLabel lbPass_warn;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JLabel lbUsername_warn;
    private javax.swing.JLabel lblogin;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void setFrameIcon() {
        Image scaled = null;
        try{
            scaled = ImageIO.read(new File("src/image/login_icon.png")).getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        }catch(IOException io_ex){
            io_ex.printStackTrace();
        }
        this.setIconImage(scaled);
    }

    private void loadingExistedDB() {
        try {
            BufferedReader instream = Files.newBufferedReader(Paths.get("src/textfile/databaseinfo.txt"));
            LineNumberReader in = new LineNumberReader(instream);
            String line;
            line = in.readLine();
            if(line.equals("0")){       // đọc dòng đầu tiên kiểm tra đã có dữ liệu về database sẵn chưa
                this.txtUsername.setEnabled(false);
                this.txtPass.setEnabled(false);
                this.btnSubmit.setEnabled(false);
            }else{                      // nếu chưa có sẵn
                this.txtUsername.setEnabled(true);
                this.txtPass.setEnabled(true);
                this.btnSubmit.setEnabled(true);
            }
            
            instream.close();
            in.close();
        } catch (IOException ex) {
            Logger.getLogger(FrLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
